### ISSUE TITLE
Channel 测试函数

### ISSUE THREAD

**Issue by valkjsaaa** [SiXinWen/cloud-code#4]

**Comment by betterenvi** [comment]
leancloud即时通讯提供hook云代码_messageReceived等支持选择收件人。所以我觉得用leanmesage是可行的，而且可发送类型丰富。

**Comment by valkjsaaa** [comment]
推送为什么类型不丰富啊....推送是 Comment 里面爱搁啥搁啥。而且 messageReceived 在 v2 里面并不支持收件人啊？v1 里面类型并不丰富啊...

**Comment by betterenvi** [comment]
v2是支持的。只是文档没写清楚。我已经实现了

**Comment by valkjsaaa** [comment]
你确定？我在 leancloud 技术支持那里发工单，他们自己都说不支持了。[链接](https://ticket.avosapps.com/tickets/553af50ae4b0072c25e8719e/threads)

**Comment by valkjsaaa** [comment]
你代码 push 上来了么？给我看下 code ？

**Comment by betterenvi** [comment]
好。等下

**Comment by betterenvi** [comment]
在develop分支。看cloud/main.js

**Comment by betterenvi** [comment]
是cloud/main.js

**Comment by betterenvi** [comment]
你把那个工单链接发一下

**Comment by betterenvi** [comment]
我看到了

**Comment by betterenvi** [comment]
在cloud/main.js：37~40行，我测试过，walker之外的人是收不到的

``` Javascript
}else if(x == 2){
    console.log("_messageReceived select");
    response.success({"toPeers": [ 'walker' ]});
}
```

**Comment by valkjsaaa** [comment]
请符合 GitHub Flavour Markdown 书写规则，写的时候该贴链接贴链接，该代码 block 用代码 block，不要 flood 大家邮件箱，可以更改的不要再发一条新的...我会清理一下这个 thread 请不要介意，本条保留，以提醒其他人。

**Comment by valkjsaaa** [comment]
我怀疑你写的代码其实还是 v1 版本的？

**Comment by betterenvi** [comment]
那我再看一下

**Comment by betterenvi** [comment]
那个工单已更新。v2也有toPeers数组。所以即时通讯v2是可以用的。

**Comment by valkjsaaa** [comment]
好的，那我们就用即时通信吧。

**Comment by valkjsaaa** [comment]
关于如何用 Commit 来 close issue: [link](https://help.github.com/articles/closing-issues-via-commit-messages/)
