### ISSUE TITLE
支持分享到微信

### ISSUE THREAD

**Issue by betterenvi** [SiXinWen/cloud-code#7]
比如，用户打开[http://sixinwen.avosapps.com/share?nid=552e853be4b036ba52441683](http://sixinwen.avosapps.com/share?nid=552e853be4b036ba52441683)，可以查看评论.
552e853be4b036ba52441683是新闻id

**Comment by extraRed** [comment]
链接有问题

**Comment by betterenvi** [comment]
已经完成
